### ISSUE TITLE
NPM Release

### ISSUE THREAD

**Issue by przemyslawpluta** [fw10/veracode-javascript-packager#5]
Is there NPM release available?

**Comment by przemyslawpluta** [comment]
Does the tool manage static upload scan or does it only package the app?

**Comment by dub-flow** [comment]
Hi przemyslawpluta, the NPM release is not ready but it's definitely something I want to do in the future. 

The app does **not** do the upload, it generates the zip which then needs to be uploaded.

**Comment by przemyslawpluta** [comment]
Thank you. NPM release would be very useful as it would allow for better workflow integration. Any suggestions in terms static upload flow?

**Comment by dub-flow** [comment]
I updated the README to make it more clear that the output of the tool is a zip that then needs to be uploaded. Thanks for bringing this up.

**Comment by dub-flow** [comment]
> Thank you. NPM release would be very useful as it would allow for better workflow integration. Any suggestions in terms static upload flow?

Agreed, having it in the NPM registry would be great and definitely something I want to do.

However, I think you can still quite easily integrate it into CI/CD though by either using one of the Releases or Docker. Would that work for you? Do you have any doubts on that?
