### ISSUE TITLE
Lock file version 3

### ISSUE THREAD

**Issue by MarcBoud** [fw10/veracode-javascript-packager#8]
I believe per the latest documentation of that lock files version 3 are supported too.  I'm not sure if the smell is outdated or my understading is wrong.

https://docs.veracode.com/r/Run_an_Agent_Based_Scan_for_NPM

**Comment by dub-flow** [comment]
Thanks for bringing this up, and it looks like you're correct! I will remove this smell check :)

**Comment by dub-flow** [comment]
Created a new release that doesn't report lockfile v3 as a "smell" anymore.
